/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	usersapi "github.com/xshoji/go-rest-openapi/usersapi/go"
)

func main() {
	log.Printf("Server started")

	UsersApiService := usersapi.NewUsersApiService()
	UsersApiController := usersapi.NewUsersApiController(UsersApiService)

	router := usersapi.NewRouter(UsersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
