/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package usersapi

import (
	"errors"
)

// UsersApiService is a service that implents the logic for the UsersApiServicer
// This service should implement the business logic for every endpoint for the UsersApi API. 
// Include any external packages or services that will be required by this service.
type UsersApiService struct {
}

// NewUsersApiService creates a default api service
func NewUsersApiService() UsersApiServicer {
	return &UsersApiService{}
}

// UsersGet - Get all users.
func (s *UsersApiService) UsersGet() (interface{}, error) {
	// TODO - update UsersGet with the required logic for this service method.
	// Add api_users_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UsersGet' not implemented")
}

// UsersPost - Create a new User
func (s *UsersApiService) UsersPost(user User) (interface{}, error) {
	// TODO - update UsersPost with the required logic for this service method.
	// Add api_users_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UsersPost' not implemented")
}

// UsersUserIdGet - Get user by ID.
func (s *UsersApiService) UsersUserIdGet(userId string) (interface{}, error) {
	// TODO - update UsersUserIdGet with the required logic for this service method.
	// Add api_users_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UsersUserIdGet' not implemented")
}
