/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package usersapi

type Country int32

// List of Country
const (
	UNKNOWN_COUNTRY Country = 0
	US Country = 1
	JP Country = 2
)
