/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package usersapi

type User struct {

	Id int32 `json:"id"`

	Name string `json:"name"`

	Nickname *string `json:"nickname,omitempty"`

	Age int32 `json:"age"`

	Birth Birth `json:"birth,omitempty"`

	Addresss Address `json:"addresss,omitempty"`

	Married *bool `json:"married,omitempty"`

	Email *string `json:"email,omitempty"`

	Website *string `json:"website,omitempty"`

	// User's sports.
	Sports []SportsType `json:"sports,omitempty"`
}
