/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package usersapi

type SportsType int32

// List of SportsType
const (
	UNKNOWN_SPORTS SportsType = 0
	SOCCER SportsType = 1
	BASEBALL SportsType = 2
	SWIMMING SportsType = 3
)
