/*
 * Sample API
 *
 * A short description of API.
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	usersapi "github.com/xshoji/go-rest-openapi/usersapi/go"
	"github.com/xshoji/go-rest-openapi/usersapi/service"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	usersApiService := service.NewUsersApiService()
	usersApiController := usersapi.NewUsersApiController(usersApiService)

	router := usersapi.NewRouter(usersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
